version: '3.8'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: divinosys-mysql
    restart: always
    environment:
      MYSQL_DATABASE: divinosys
      MYSQL_USER: divino
      MYSQL_PASSWORD: divino123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./pdv_db.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - divinosys-network

  # Web Application
  web:
    build: .
    container_name: divinosys-web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=divinosys
      - DB_USER=divino
      - DB_PASS=divino123
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - APP_URL=http://localhost:8081
      - APP_ENV=development
      - APP_PROTOCOL=http
      - FORCE_HTTPS=false
      - IS_PRODUCTION=false
      - APP_NAME=DivinoSys
      - APP_VERSION=2.0
      - SESSION_SECURE=false
      - SESSION_HTTPONLY=true
      - SESSION_LIFETIME=120
      - UPLOAD_MAX_SIZE=64M
      - UPLOAD_ALLOWED_TYPES=jpg,jpeg,png,gif,pdf,doc,docx
      - TZ=America/Sao_Paulo
    depends_on:
      - db
    networks:
      - divinosys-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: divinosys-phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root123
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - divinosys-network

networks:
  divinosys-network:
    driver: bridge

volumes:
  mysql_data: 